apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site
  labels:
    app: simple-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      containers:
        - name: simple-site
          image: robinyaghi/simple-site:v1   # ðŸ‘ˆ your Docker Hub image
          ports:
            - containerPort: 80

