name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.html"
      - "**/*.css"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecom-gitops:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom-gitops:${{ github.sha }}

      - name: Clone GitOps repo
        run: |
          git clone https://github.com/Web-robs/ecom.git gitops

      - name: Update Helm chart image tag
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" gitops/simple-site-chart/values.yaml

      - name: Commit & Push changes to GitOps repo
        run: |
          cd gitops
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push

